## Домашнее задание: библиотека Numpy

In [ ]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# =========================
#         Решение:
# =========================
print(np.ndim(a)) # 2
print(np.ndim(b)) # 2

print(np.shape(a)) # (100, 100)
print(np.shape(b)) # (100, 100)
# ========================

print(a)
print(b)

2
2
(100, 100)
(100, 100)
[[0.11475967 0.93733962 0.69246886 ... 0.84078669 0.73970915 0.33097482]
 [0.01948255 0.56563724 0.23365614 ... 0.45104822 0.5467379  0.92549766]
 [0.07689683 0.83033002 0.70291142 ... 0.42483418 0.44942251 0.12851113]
 ...
 [0.21200869 0.75220274 0.09895769 ... 0.78900422 0.01424403 0.89570745]
 [0.63917851 0.75704723 0.08470176 ... 0.08471    0.13671536 0.13480023]
 [0.69220409 0.92239794 0.15200475 ... 0.53942951 0.36543839 0.16285985]]
[[0.75352655 0.36698595 0.08597986 ... 0.70277632 0.82754832 0.54373404]
 [0.51133002 0.46042418 0.91632597 ... 0.74894705 0.7200568  0.65460356]
 [0.86046681 0.32389703 0.48467064 ... 0.82960348 0.75887715 0.57889177]
 ...
 [0.35512572 0.24518576 0.27988906 ... 0.20123414 0.36677494 0.32403905]
 [0.36661965 0.84403939 0.6732293  ... 0.82461949 0.07015738 0.68934597]
 [0.73672559 0.58375545 0.34382373 ... 0.9095626  0.90481997 0.71785621]]


In [ ]:
def mult(a, b):
    """
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    a = a.tolist()
    b = b.tolist()
    size = len(a)

    # По условию размерность size x size => квадратная матрица => проверок на возможность проведения операции умножения не делаю
    c = [[0 for _ in range(len(a))] for _ in range(len(b))]

    # Умножение матриц
    for i in range(size):           # Каждая строка матрицы А
        for j in range(size):       # Каждый стобец матрицы B
            for k in range(size):   # Каждый элемент столбца матрицы B и строчки матрицы A
                c[i][j] += a[i][k] * b[k][j]
    return c

In [ ]:
def np_mult(a, b):
    """
    a: np.array[size, size] --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size] --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    c = np.dot(a, b)
    return c

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 221 ms, sys: 3.1 ms, total: 224 ms
Wall time: 225 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 449 µs, sys: 2.88 ms, total: 3.33 ms
Wall time: 6.6 ms


In [ ]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.

Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без.

Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.20179809 0.03161764 0.86618014] [0.81729743 0.73473166 0.92410321]


In [ ]:
def scalar_product(a, b):
    """
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy
    """
    ans = 0
    for i in range(len(a)):
      ans += a[i] * b[i]
    return ans


scalar_product(a, b)

0.988599384906313

In [ ]:
def np_scalar_product(a,b):
    """
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """
    return(np.dot(a, b))

np_scalar_product(a, b)

0.988599384906313

In [ ]:
%time
product_1 = scalar_product(a,b)
%time
product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

CPU times: user 6 µs, sys: 1 µs, total: 7 µs
Wall time: 7.63 µs
CPU times: user 6 µs, sys: 1 µs, total: 7 µs
Wall time: 6.44 µs


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находит сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [ ]:
def np_diag_2k(a):
    """
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy
    """
    summa = 0
    d = np.diagonal(a)   # Только диагональные элементы
    summa = np.sum(d[d % 2 == 0])  # Суммирую только четные элементы
    return summa

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 6, 2, 4, 4],
       [2, 9, 2, 8, 9],
       [3, 9, 7, 8, 6],
       [7, 1, 8, 5, 7],
       [4, 6, 1, 2, 6]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 92 µs, sys: 17 µs, total: 109 µs
Wall time: 113 µs


12

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​

In [ ]:
def cumsum(A):
    """
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy
    """
    return np.cumsum(A, axis=1)

In [ ]:
# зададим некоторую последовательность и проверим ее на вашей функции.

# Почему последовательность????? Надо же матрицу
A = sps.uniform.rvs(size=10**3)
print(np.shape(A))    # (1000, )

A = sps.uniform.rvs(size=(2, 10**3))
print(np.shape(A))    # (2, 1000)

%time
S2 = cumsum(A)

(1000,)
(2, 1000)
CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.39 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [ ]:
from copy import copy
def np_transformation(X, a=1):
    """
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке,
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy
    """
    result = []
    for x in X:
        new_x = np.copy(x)
        new_x[1::2] = a
        new_x[0::2] = np.power(new_x[0::2], 3)
        new_x = new_x[::-1]

        combined_row = np.concatenate((x, new_x))
        result.append(combined_row)

    return np.array(result)

In [ ]:
X = np.array([[i for i in range(1, 10, 2)]])
%time
S2 = np_transformation(X, 5)
S2

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.39 µs


array([[  1,   3,   5,   7,   9, 729,   5, 125,   5,   1]])